name: MoneyTrans
version: '${project.version}'
main: dev.enderteam.moneytrans.MoneyTrans
api-version: 1.18
authors: [ EnderTeam ]
depend:
  - Vault

commands:
  moneytrans:
    permission: moneytrans
    aliases:
      - mt
    usage: sadawd
permissions:
  moneytrans:
    default: op
    description: moneytrans